using System;
using System.Collections.Generic;
using System.Net;
using Flinks.CSharp.SDK.Model;
using Flinks.CSharp.SDK.Model.AccountSummary;
using Flinks.CSharp.SDK.Model.Authorization;
using Flinks.CSharp.SDK.Model.Constant;
using Flinks.CSharp.SDK.Model.Shared;
using Newtonsoft.Json;
using RestSharp;
using static System.Net.HttpStatusCode;

namespace Flinks.CSharp.SDK
{
    public class FlinksClient
    {
        private string CustomerId { get; }
        private string Endpoint { get; }
        private string BaseUrl => GetBaseUrl();
        private AuthorizationRequestBody AuthorizationBody { get; set; }
        private RestClient RestClient { get; }
        public AuthorizationStatus AuthorizationStatus { get; set; }

        private readonly JsonSerializerSettings _jsonSerializationSettings = new JsonSerializerSettings()
        {
            //Default Serializer used to put the JSON sent over the requests in the right format.
            NullValueHandling = NullValueHandling.Ignore
        };

        /// <summary>
        /// Flinks client object
        /// </summary>
        /// <param name="customerId">Flinks customer ID.</param>
        /// <param name="endpoint">Flinks client endpoint URL.</param>
        public FlinksClient(string customerId, string endpoint)
        {
            CustomerId = customerId;
            Endpoint = endpoint;

            RestClient = new RestClient(BaseUrl);
        }

        /// <summary>
        /// Authorize method is used to call the Authorize endpoint at Flinks API. Must be used to start the Authorize process.
        /// </summary>
        /// <param name="institution">Institution (bank) where the you want to retrieve information from.</param>
        /// <param name="userName">The username used by your client in the banking account you want to retrieve information from.</param>
        /// <param name="password">The password used by your client int the banking account you want to retrieve information from.</param>
        /// <param name="save">Used if you want to save the request within the Flinks API.</param>
        /// <param name="mostRecentCached"></param>
        /// <param name="withMfaQuestions"></param>
        /// <param name="requestLanguage"></param>
        /// <param name="tag"></param>
        /// <returns>An AuthorizationResponse object contained information regarding the status of the authorization process.</returns>
        public AuthorizationResponse Authorize(string institution, string userName, string password, bool? save, bool? mostRecentCached, bool? withMfaQuestions, RequestLanguage? requestLanguage, string tag = null)
        {
            GenerateAuthorizeRequestBody(institution, userName, password, save, mostRecentCached, withMfaQuestions, requestLanguage, tag);

            var request = GetBaseRequest(EndpointConstant.Authorize, Method.POST);
            request.AddParameter(FlinksSettingsConstant.ApplicationJsonUTF8, JsonConvert.SerializeObject(AuthorizationBody, _jsonSerializationSettings), ParameterType.RequestBody);

            var response = RestClient.Execute(request);

            SetClientAuthorizationStatus(response.StatusCode);

            var apiResponse = JsonConvert.DeserializeObject<AuthorizationResponse>(response.Content);

            apiResponse.AuthorizationStatus = AuthorizationStatus;

            return apiResponse;
        }

        /// <summary>
        /// Used to answer the MFA questions and proceed with the authorization process.
        /// </summary>
        /// <param name="requestId">The requestId generated by the original call to the Authorize method.</param>
        /// <param name="securityChallenges">A list with the SecurityChallanges provided by the original Authorize method filled with the answers for the MFA questions.</param>
        /// <returns></returns>
        public AuthorizationResponse AnswerMfaQuestionsAndAuthorize(string requestId, List<SecurityChallenge> securityChallenges)
        {
            var mfaAnswers = new Dictionary<string, List<string>>();

            foreach (var securityChallenge in securityChallenges)
            {
                mfaAnswers.Add(securityChallenge.Prompt, new List<string>()
                {
                    securityChallenge.Answer
                });
            }

            AuthorizationBody = new AuthorizationRequestBody()
            {
                RequestId = requestId,
                SecurityResponses = mfaAnswers
            };

            var request = GetBaseRequest(EndpointConstant.Authorize, Method.POST);
            request.AddParameter(FlinksSettingsConstant.ApplicationJsonUTF8, JsonConvert.SerializeObject(AuthorizationBody, _jsonSerializationSettings), ParameterType.RequestBody);

            var response = RestClient.Execute(request);

            SetClientAuthorizationStatus(response.StatusCode);

            var apiResponse = JsonConvert.DeserializeObject<AuthorizationResponse>(response.Content);

            apiResponse.AuthorizationStatus = AuthorizationStatus;

            return apiResponse;
        }

        /// <summary>
        /// Used to get summary infos from Flinks API. The client must be Authorized before calling this method.
        /// </summary>
        /// <param name="requestId"></param>
        /// <returns></returns>
        public AccountSummary GetSummary(string requestId)
        {
            var request = GetBaseRequest(EndpointConstant.GetAccountsSummary, Method.POST);
            request.AddParameter(FlinksSettingsConstant.ApplicationJsonUTF8, JsonConvert.SerializeObject(new AuthorizationRequestBody()
            {
                RequestId = requestId
            }, _jsonSerializationSettings), ParameterType.RequestBody);

            var response = RestClient.Execute(request);

            SetClientAuthorizationStatus(response.StatusCode);

            var apiResponse = JsonConvert.DeserializeObject<AccountSummary>(response.Content);

            apiResponse.AuthorizationStatus = AuthorizationStatus;

            return apiResponse;
        }

        #region Util
        private string GetBaseUrl()
        {
            var baseUrl = EndpointConstant.BaseUrl;

            baseUrl = baseUrl.Replace(FlinksSettingsConstant.Endpoint, Endpoint).Replace(FlinksSettingsConstant.CustomerId, CustomerId);

            return baseUrl;
        }

        private void GenerateAuthorizeRequestBody(string institution, string userName, string password, bool? save, bool? mostRecentCached, bool? withMfaQuestions, RequestLanguage? requestLanguage, string tag = null)
        {
            AuthorizationBody = new AuthorizationRequestBody()
            {
                UserName = userName,
                Password = password,
                Institution = institution,
                Save = save?.ToString().ToLower(),
                MostRecentCached = mostRecentCached?.ToString().ToLower(),
                WithMfaQuestions = withMfaQuestions?.ToString().ToLower(),
                Language = requestLanguage?.ToString().ToLower(),
                Tag = tag
            };
        }

        private static RestRequest GetBaseRequest(string endpoint, Method method)
        {
            var request = new RestRequest(endpoint, method);

            request.Parameters.Clear();
            request.AddHeader(FlinksSettingsConstant.ContentType, FlinksSettingsConstant.ApplicationJsonUTF8);
            return request;
        }

        private void SetClientAuthorizationStatus(HttpStatusCode httpStatusCode)
        {
            var authorizationStatus = AuthorizationStatus.UNKNOWN;

            switch (httpStatusCode)
            {
                case NonAuthoritativeInformation:
                    {
                        authorizationStatus = AuthorizationStatus.PENDING_MFA_ANSWERS;

                        break;
                    }
                case OK:
                    {
                        authorizationStatus = AuthorizationStatus.AUTHORIZED;

                        break;
                    }

                default:
                    {
                        authorizationStatus = AuthorizationStatus.UNKNOWN;

                        break;
                    }
            }

            AuthorizationStatus = authorizationStatus;
        }
        #endregion
    }
}
